/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FlightSearchTab {
        "tabname": string;
        "tabswitchname": string;
        "text": string;
    }
}
declare global {
    interface HTMLFlightSearchTabElement extends Components.FlightSearchTab, HTMLStencilElement {
    }
    var HTMLFlightSearchTabElement: {
        prototype: HTMLFlightSearchTabElement;
        new (): HTMLFlightSearchTabElement;
    };
    interface HTMLElementTagNameMap {
        "flight-search-tab": HTMLFlightSearchTabElement;
    }
}
declare namespace LocalJSX {
    interface FlightSearchTab {
        "tabname"?: string;
        "tabswitchname"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "flight-search-tab": FlightSearchTab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flight-search-tab": LocalJSX.FlightSearchTab & JSXBase.HTMLAttributes<HTMLFlightSearchTabElement>;
        }
    }
}
